### ISSUE TITLE
gr-APRS/Examples/epy_block_0.py", line 40, in handle_msg

### ISSUE THREAD

**Issue by ycchae** [agrositters/agrositterPurdue#1]
OO* MESSAGE DEBUG PRINT PDU VERBOSE *
()
pdu_length = 66
contents = 
0000: 82 a0 9e a8 a4 64 e0 ae 62 82 ae 40 40 e0 ae 92 
0010: 88 8a 62 40 62 ae 92 88 8a 64 40 63 03 f0 3e 54 
0020: 68 69 73 20 69 73 20 52 61 64 69 6f 53 68 69 65 
0030: 6c 64 20 74 65 73 74 20 6d 65 73 73 61 67 65 20 
0040: 23 37 
***********************************
handler caught exception: 'module' object has no attribute 'from_bytes'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/gr/gateway.py", line 73, in eval
    try: self._callback(arg)
  File "/home/sdr/yun/gr-APRS/Examples/epy_block_0.py", line 40, in handle_msg
    pkt = packet.from_bytes(msg)
AttributeError: 'module' object has no attribute 'from_bytes'
handler caught exception: in method 'block_gw_message_type_stop_args_return_value_set', argument 2 of type 'bool'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/gr/gateway.py", line 55, in eval
    try: self._callback()
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/gr/gateway.py", line 238, in __gr_block_handle
    self.__message.stop_args_return_value = self.stop()
TypeError: in method 'block_gw_message_type_stop_args_return_value_set', argument 2 of type 'bool'
terminate called after throwing an instance of 'Swig::DirectorMethodException'
  what():  SWIG director method error. Error detected when calling 'feval_ll.eval'

ERROR MESSAGE

**Comment by chae-yc** [comment]
OOOO* MESSAGE DEBUG PRINT PDU VERBOSE *
()
pdu_length = 67
contents = 
0000: 82 a0 9e a8 a4 64 e0 ae 62 82 ae 40 40 e0 ae 92 
0010: 88 8a 62 40 62 ae 92 88 8a 64 40 63 03 f0 3e 54 
0020: 68 69 73 20 69 73 20 52 61 64 69 6f 53 68 69 65 
0030: 6c 64 20 74 65 73 74 20 6d 65 73 73 61 67 65 20 
0040: 23 37 34 
***********************************
handler caught exception: 'module' object has no attribute 'from_bytes'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/gr/gateway.py", line 73, in eval
    try: self._callback(arg)
  File "/home/sdr/yun/gr-APRS/Examples/epy_block_0.py", line 40, in handle_msg
    pkt = packet.from_bytes(msg)
AttributeError: 'module' object has no attribute 'from_bytes'
handler caught exception: in method 'block_gw_message_type_stop_args_return_value_set', argument 2 of type 'bool'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/gr/gateway.py", line 55, in eval
    try: self._callback()
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/gr/gateway.py", line 238, in __gr_block_handle
    self.__message.stop_args_return_value = self.stop()
TypeError: in method 'block_gw_message_type_stop_args_return_value_set', argument 2 of type 'bool'
terminate called after throwing an instance of 'Swig::DirectorMethodException'
  what():  SWIG director method error. Error detected when calling 'feval_ll.eval'

SECOND ERROR
